all: client6
client1: client1.cc
	g++ -o $@ $^ -std=c++17
client2: client2.cc
	g++ -o $@ $^ -std=c++17
client3: client3.cc
	g++ -o $@ $^ -std=c++17
client4: client4.cc
	g++ -o $@ $^ -std=c++17
client5: client5.cc
	g++ -o $@ $^ -std=c++17
client6: client6.cc
	g++ -o $@ $^ -std=c++17

.PHONY:clean
clean:
	rm -f client6